services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RSLIDAR_SDK_REF: ${RSLIDAR_SDK_REF:-main}
        RSLIDAR_MSG_REF: ${RSLIDAR_MSG_REF:-main}
        RSLIDAR_LIDAR_TYPE: ${RSLIDAR_LIDAR_TYPE:-RSAIRY}
        RSLIDAR_MSOP_PORT: ${RSLIDAR_MSOP_PORT:-6699}
        RSLIDAR_DIFOP_PORT: ${RSLIDAR_DIFOP_PORT:-7788}
        RSLIDAR_IMU_PORT: ${RSLIDAR_IMU_PORT:-6688}
    container_name: ros2_humble_slam_jetson
    network_mode: host
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CYCLONEDDS_URI=file:///home/linda/cyclone_dds.xml  # optional
    volumes:
      - ../src:/home/linda/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../cyclone_dds.xml:/home/linda/cyclone_dds.xml      # optional
    devices:
      - /dev/video0:/dev/video0
      #- /dev/ttyUSB0:/dev/ttyUSB0
    device_cgroup_rules:
      - 'c 189:* rmw'
      - 'c 81:* rmw'
    stdin_open: true
    tty: true